[build]
command = "cd backend && npm install"

[deploy]
startCommand = "cd backend && node server.js"
healthcheckPath = "/"
healthcheckTimeout = 120
restartPolicyType = "ON_FAILURE"

[variables]
NODE_ENV = "production"