[build]
command = "cd backend && npm install"

[deploy]
startCommand = "cd backend && npm start"
healthcheckPath = "/" 
healthcheckTimeout = 60
restartPolicyType = "ON_FAILURE"

[variables]
NODE_ENV = "production"
PORT = "5000"